export enum Language {
  English = "en",
  Anglish = "an",
}

export enum Source {
  Wordnet = "wordnet",
  User = "user",
}

export enum WordnetPOS {
  Noun = "n",
  Verb = "v",
  Adjective = "a",
  Satellite = "s",
  Adverb = "r",
}

export enum OriginLanguage {
  PIE = "Proto-Indo-European",
  PG = "Proto-Germanic",
  PN = "Proto-Norse",
  ON = "Old Norse",
  OWN = "Old West Norse",
  OIC = "Old Icelandic",
  MIC = "Middle Icelandic",
  IC = "Modern Icelandic",
  ONO = "Old Norwegian",
  MNO = "Middle Norwegian",
  NO = "Norwegian",
  OFO = "Old Faroese",
  FO = "Faroese",
  ONN = "Old Norn",
  NN = "Norn",
  OEN = "Old East Norse",
  EOD = "Early Old Danish",
  LOD = "Late Old Danish",
  DN = "Danish",
  EOS = "Early Old Swedish",
  LOS = "Late Old Swedish",
  SW = "Swedish",
  EOG = "Early Old Gutnish",
  LOG = "Late Old Gutnish",
  GU = "Gutnish",
  ED = "Elfdalian",
  PWG = "Proto-West Germanic",
  OE = "Old English",
  OEM = "Old English (Mercian Dialect)",
  OENU = "Old English (Northumbrian Dialect)",
  ME = "Middle English",
  ENE = "Early New (Modern) English",
  NE = "New (Modern) English",
  ES = "Early Scots",
  MS = "Middle Scots",
  NS = "New Scots",
  OF = "Old Frisian",
  MF = "Middle Frisian",
  NF = "North Frisian",
  WF = "West Frisian",
  SF = "Saterland Frisian",
  OS = "Old Saxon",
  MLS = "Middle Low Saxon",
  LS = "Low Saxon",
  OFK = "Old Frankish",
  OLF = "Old Low Franconian",
  MNL = "Middle Dutch",
  NL = "Modern Dutch",
  AF = "Afrikaans",
  OHG = "Old High German",
  MHG = "Middle High German",
  ENHG = "Early New High German",
  NHG = "New High German",
  YD = "Yiddish",
  LO = "Lombardic",
  PEG = "Proto-East Germanic",
  GO = "Gothic",
  VA = "Vandalic",
  BU = "Burgundian",
  CG = "Crimean Gothic",
  NP = "New Persian",
  FN = "Finnish",
}

export enum OriginCode {
  ProtoIndoEuropean = "PIE",
  ProtoGermanic = "PG",
  ProtoNorse = "PN",
  OldNorse = "ON",
  OldWestNorse = "OWN",
  OldIcelandic = "OIC",
  MiddleIcelandic = "MIC",
  ModernIcelandic = "IC",
  OldNorwegian = "ONO",
  MiddleNorwegian = "MNO",
  Norwegian = "NO",
  OldFaroese = "OFO",
  Faroese = "FO",
  OldNorn = "ONN",
  Norn = "NN",
  OldEastNorse = "OEN",
  EarlyOldDanish = "EOD",
  LateOldDanish = "LOD",
  Danish = "DN",
  EarlyOldSwedish = "EOS",
  LateOldSwedish = "LOS",
  Swedish = "SW",
  EarlyOldGutnish = "EOG",
  LateOldGutnish = "LOG",
  Gutnish = "GU",
  Elfdalian = "ED",
  ProtoWestGermanic = "PWG",
  OldEnglish = "OE",
  OldEnglishMercian = "OEM",
  OldEnglishNorthumbrian = "OENU",
  MiddleEnglish = "ME",
  EarlyNewModernEnglish = "ENE",
  NewModernEnglish = "NE",
  EarlyScots = "ES",
  MiddleScots = "MS",
  NewScots = "NS",
  OldFrisian = "OF",
  MiddleFrisian = "MF",
  NorthFrisian = "NF",
  WestFrisian = "WF",
  SaterlandFrisian = "SF",
  OldSaxon = "OS",
  MiddleLowSaxon = "MLS",
  LowSaxon = "LS",
  OldFrankish = "OFK",
  OldLowFranconian = "OLF",
  MiddleDutch = "MNL",
  ModernDutch = "NL",
  Afrikaans = "AF",
  OldHighGerman = "OHG",
  MiddleHighGerman = "MHG",
  EarlyNewHighGerman = "ENHG",
  NewHighGerman = "NHG",
  Yiddish = "YD",
  Lombardic = "LO",
  ProtoEastGermanic = "PEG",
  Gothic = "GO",
  Vandalic = "VA",
  Burgundian = "BU",
  CrimeanGothic = "CG",
  NewPersian = "NP",
  Finnish = "FN",
}

export enum OriginKind {
  Inherited = "inherited",
  Derived = "derived",
  Borrowed = "borrowed",
  Cognate = "cognate",
  Compound = "compound",
  Calque = "calque"
}

export interface WordOrigin {
  lang: OriginLanguage,
  kind: OriginKind,
  form: string // The source word form. Ex: "bōtuz"
}

export enum SenseRelation {
  Agent = "agent",
  Also = "also",
  Antonym = "antonym",
  BodyPart = "body_part",
  ByMeansOf = "by_means_of",
  Derivation = "derivation",
  Destination = "destination",
  Event = "event",
  Exemplifies = "exemplifies",
  Instrument = "instrument",
  Location = "location",
  Material = "material",
  Participle = "participle",
  Pertainym = "pertainym",
  Property = "property",
  Result = "result",
  Similar = "similar",
  State = "state",
  Undergoer = "undergoer",
  Uses = "uses",
  Vehicle = "vehicle",
}

export enum SynsetRelation {
  Also = "also",
  Attribute = "attribute",
  Causes = "causes",
  DomainRegion = "domain_region",
  DomainTopic = "domain_topic",
  Entails = "entails",
  Exemplifies = "exemplifies",
  Hypernym = "hypernym",
  MeroMember = "mero_member",
  MeroPart = "mero_part",
  MeroSubstance = "mero_substance",
  Similar = "similar",
}