export enum WordnetPOS {
  Noun = "n",
  Verb = "v",
  Adjective = "a",
  Satellite = "s",
  Adverb = "r",
}


export enum OriginLanguage {
  PIE = "Proto-Indo-European",
  PG = "Proto-Germanic",
  PN = "Proto-Norse",
  ON = "Old Norse",
  OWN = "Old West Norse",
  OIC = "Old Icelandic",
  MIC = "Middle Icelandic",
  IC = "Modern Icelandic",
  ONO = "Old Norwegian",
  MNO = "Middle Norwegian",
  NO = "Norwegian",
  OFO = "Old Faroese",
  FO = "Faroese",
  ONN = "Old Norn",
  NN = "Norn",
  OEN = "Old East Norse",
  EOD = "Early Old Danish",
  LOD = "Late Old Danish",
  DN = "Danish",
  EOS = "Early Old Swedish",
  LOS = "Late Old Swedish",
  SW = "Swedish",
  EOG = "Early Old Gutnish",
  LOG = "Late Old Gutnish",
  GU = "Gutnish",
  ED = "Elfdalian",
  PWG = "Proto-West Germanic",
  OE = "Old English",
  OEM = "Old English (Mercian Dialect)",
  OENU = "Old English (Northumbrian Dialect)",
  ME = "Middle English",
  ENE = "Early New (Modern) English",
  NE = "New (Modern) English",
  ES = "Early Scots",
  MS = "Middle Scots",
  NS = "New Scots",
  OF = "Old Frisian",
  MF = "Middle Frisian",
  NF = "North Frisian",
  WF = "West Frisian",
  SF = "Saterland Frisian",
  OS = "Old Saxon",
  MLS = "Middle Low Saxon",
  LS = "Low Saxon",
  OFK = "Old Frankish",
  OLF = "Old Low Franconian",
  MNL = "Middle Dutch",
  NL = "Modern Dutch",
  AF = "Afrikaans",
  OHG = "Old High German",
  MHG = "Middle High German",
  ENHG = "Early New High German",
  NHG = "New High German",
  YD = "Yiddish",
  LO = "Lombardic",
  PEG = "Proto-East Germanic",
  GO = "Gothic",
  VA = "Vandalic",
  BU = "Burgundian",
  CG = "Crimean Gothic",
  NP = "New Persian",
  FN = "Finnish",
}

export enum OriginKind {
  Inherited = "inherited",
  Derived = "derived",
  Borrowed = "borrowed",
  Cognate = "cognate",
  Compound = "compound",
  Calque = "calque"
}

export interface WordOrigin {
  lang: OriginLanguage,
  kind: OriginKind,
  form: string // The source word form. Ex: "bōtuz"
}
