export type EtymologyTemplateName
  = | "!"
    | "!-"
    | "'"
    | "|"
    | "-a-o-e"
    | "-a-o-x"
    | "-a-us-x"
    | "="
    | "A.D."
    | "AD"
    | "B.C."
    | "B.C.E."
    | "BC"
    | "BCE"
    | "C"
    | "C."
    | "C.E."
    | "CE"
    | "Commonscat"
    | "EtymOnLine"
    | "Genericized trademark"
    | "IPA"
    | "IPAfont"
    | "IPAlink"
    | "IPAsym"
    | "OCLC"
    | "PIE root box"
    | "PIE word"
    | "PMID"
    | "Q"
    | "SIC"
    | "U"
    | "U:en:imitating-challenged"
    | "abbr"
    | "abbrev"
    | "abbreviation of"
    | "abor"
    | "acronym"
    | "acronym of"
    | "adapted borrowing"
    | "af"
    | "affix"
    | "aka"
    | "also"
    | "alt"
    | "alt form"
    | "alt sp"
    | "alter"
    | "alternative case form of"
    | "alternative form of"
    | "alternative spelling of"
    | "anchor"
    | "angbr"
    | "ante"
    | "aphetic form"
    | "aphetic form of"
    | "apocopic form"
    | "ar-active participle"
    | "ar-form"
    | "ar-instance noun"
    | "ar-passive participle"
    | "ar-root"
    | "att"
    | "audio"
    | "back-form"
    | "back-formation"
    | "backform"
    | "backformation"
    | "bf"
    | "blend"
    | "blockquote"
    | "book of the Bible"
    | "bor"
    | "bor+"
    | "bor-lite"
    | "borrowed"
    | "c"
    | "c."
    | "cal"
    | "calque"
    | "cap"
    | "caps"
    | "categorize"
    | "century"
    | "circa"
    | "circa2"
    | "cite tweet"
    | "cleanup"
    | "clear"
    | "clip"
    | "clip of"
    | "clipping"
    | "clipping of"
    | "clq"
    | "cog"
    | "cog-lite"
    | "cognate"
    | "coin"
    | "coinage"
    | "coined"
    | "col"
    | "col-top"
    | "com"
    | "com+"
    | "commonscat"
    | "compound"
    | "compound+"
    | "con"
    | "confix"
    | "contr"
    | "contraction"
    | "contraction of"
    | "datedef"
    | "dbt"
    | "defdate"
    | "denominal verb"
    | "der"
    | "der+"
    | "der-lite"
    | "der-lite/lang"
    | "dercat"
    | "derived"
    | "desc"
    | "deverbal"
    | "diminutive of"
    | "displaced"
    | "doi"
    | "doublet"
    | "eggcorn of"
    | "egy-h"
    | "elements"
    | "elements/dowork"
    | "ellipsis"
    | "ellipsis of"
    | "emojipic"
    | "en-noun"
    | "enPRchar"
    | "etydate"
    | "etydate/l2"
    | "etydate/the"
    | "etymid"
    | "etymon"
    | "eye dialect of"
    | "fa-xlit"
    | "false cognate"
    | "feminine of"
    | "folklore"
    | "frac"
    | "from"
    | "g"
    | "genericized trademark"
    | "gentrade"
    | "gl"
    | "gloss"
    | "glossary"
    | "grc-ark"
    | "grc-att"
    | "grc-ion"
    | "he-l"
    | "he-m"
    | "he-root"
    | "he-root-link"
    | "head"
    | "hot word"
    | "hyph"
    | "hyphenation"
    | "i"
    | "ic"
    | "infix"
    | "infl of"
    | "inh"
    | "inh+"
    | "inh-lite"
    | "inherited"
    | "init"
    | "init of"
    | "initialism"
    | "initialism of"
    | "internationalism"
    | "interwikt"
    | "italic"
    | "ja-blend"
    | "ja-com"
    | "ja-compound"
    | "ja-l"
    | "ja-l/helper"
    | "ja-r"
    | "ja-ryk"
    | "key press/core"
    | "ko-l"
    | "l/vi/Latn"
    | "label"
    | "lang"
    | "langname"
    | "langname-mention"
    | "lb"
    | "lbor"
    | "learned borrowing"
    | "lena"
    | "letter_disp2"
    | "lg"
    | "listen"
    | "listen/core"
    | "lit"
    | "ltc-l"
    | "lw"
    | "m+"
    | "m-g"
    | "m-lite"
    | "mdash"
    | "mention-gloss"
    | "metathesis"
    | "monospace"
    | "multiple image"
    | "n-g"
    | "name translit"
    | "named-after"
    | "named-after/list"
    | "nb..."
    | "nbsp"
    | "ncog"
    | "ng"
    | "noitalic"
    | "nom"
    | "nominalization"
    | "non-gloss"
    | "non-lemma"
    | "noncog"
    | "nonlemma"
    | "nonstandard spelling of"
    | "nowrap"
    | "number box"
    | "obor"
    | "obsolete form of"
    | "obsolete spelling of"
    | "och-l"
    | "onom"
    | "onomatopoeia"
    | "onomatopoeic"
    | "or else"
    | "ordinal"
    | "orth"
    | "overline"
    | "pagetype"
    | "partial calque"
    | "pb"
    | "pcal"
    | "pclq"
    | "pedia"
    | "pedialite"
    | "person"
    | "phono-semantic matching"
    | "picdiclabel/new"
    | "piecewise doublet"
    | "piecewise_doublet"
    | "pl"
    | "pre"
    | "pre-Germanic"
    | "prefix"
    | "present participle of"
    | "pronunciation spelling of"
    | "pseudo-acronym"
    | "pseudo-loan"
    | "pseudoloan"
    | "psm"
    | "pwdbt"
    | "q"
    | "q-g"
    | "qf"
    | "qual"
    | "qualifier"
    | "quote"
    | "quote-av"
    | "quote-book"
    | "quote-gloss"
    | "quote-journal"
    | "quote-text"
    | "quote-web"
    | "rdp"
    | "rebracketing"
    | "reduplication"
    | "reduplication of"
    | "ref"
    | "reflist"
    | "refn"
    | "retronym"
    | "rhymes"
    | "root"
    | "ryu-r"
    | "s"
    | "section link"
    | "see desc"
    | "semantic loan"
    | "sense"
    | "senseno"
    | "sequence box"
    | "shitgibbon"
    | "short for"
    | "sic"
    | "sl"
    | "slbor"
    | "small"
    | "small caps"
    | "smallcaps"
    | "smc"
    | "sound symbolic"
    | "sound-symbolic"
    | "spelling pronunciation"
    | "spoonerism"
    | "ss"
    | "str index-lite/logic"
    | "str left"
    | "str len-lite"
    | "str len-lite/core"
    | "str sub-lite"
    | "str sub-lite/2"
    | "str_index-lite"
    | "sub"
    | "suf"
    | "suffix"
    | "sup"
    | "surf"
    | "surface analysis"
    | "surface etymology"
    | "syc-root"
    | "syncopic form"
    | "syncopic form of"
    | "synonym of"
    | "t"
    | "t2i-Egyd"
    | "taxfmt"
    | "taxlink"
    | "text float box"
    | "timeline:generations/reference"
    | "topics"
    | "trademark erosion"
    | "translit"
    | "transliteration"
    | "ubor"
    | "uder"
    | "unadapted borrowing"
    | "unc"
    | "uncertain"
    | "univ"
    | "univerbation"
    | "unk"
    | "unknown"
    | "upright"
    | "vern"
    | "vi-l"
    | "wasei eigo"
    | "wikidata"
    | "wikidata lexeme"
    | "wikiquote"
    | "wikispecies"
    | "word"
    | "wp"
    | "wsource"
    | "xlit"
    | "zh-l"
    | "zh-m"
    | "…";

export const EtymologyTemplateAlias: Record<string, EtymologyTemplateName[]> = {
  Inherited: ["inh", "inh+"],
  Derived: ["der", "der+", "uder"],
  Borrowed: ["bor", "bor+", "ubor"],
  Cognate: ["cog"],
  Compound: ["compound"],
  Calque: ["cal", "calque"],
} as const;

export interface KaikkiEntry {
  pos: string;
  head_templates: {
    name: string;
    args: Record<string, string>;
    expansion: string;
  }[];
  forms: { form: string; tags: string[] }[];
  wikipedia: string[];
  sounds: Sound[];
  hyphenation: string[];
  etymology_text: string;
  etymology_templates: {
    name: EtymologyTemplateName;
    args: Record<string, string>;
    expansion: string;
  }[];
  word: string;
  lang: string;
  lang_code: string;
  synonyms: { tags: string[]; word: string; _dis1: string }[];
  derived: { word: string; _dis1: string; taxonomic?: string }[];
  related: { word: string; _dis1: string; taxonomic?: string }[];
  senses: {
    examples: { text: string; ref?: string; type: string }[];
    wikidata: string[];
    senseid: string[];
    links: string[][];
    glosses?: string[];
    raw_glosses: string[];
    tags: string[];
    topics: string[];
    id: string;
    categories: {
      name: string;
      kind: string;
      parents: string[];
      source: string;
      orig?: string;
      langcode?: string;
      _dis?: string;
    }[];
    translations: {
      lang: string;
      code: string;
      sense: string;
      roman?: string;
      english?: string;
      tags?: string[];
      word: string;
      _dis1: string;
    }[];
    synonyms: { tags: string[]; sense: string; word: string; _dis1: string }[];
  }[];
}

export interface Sound {
  ipa?: string;
  rhymes?: string;
  audio?: string;
  text?: string;
  tags?: string[];
  ogg_url?: string;
  mp3_url?: string;
  enpr?: string;
}
